spring:
  application:
    name: crypto_mining

  datasource:
    url: jdbc:mysql://121.40.215.191:3306/mining?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: test
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      # 连接最大存活时间
      max-lifetime: 1800000  # 30分钟
      # 空闲连接超时时间（需小于 max-lifetime）
      idle-timeout: 600000   # 10分钟
      # 连接验证查询
      connection-test-query: "SELECT 1"

  cache:
    type: redis

  redis:
    database: 2
    host: 121.40.215.191
    port: 6379
    password: cS5bXr9o
    timeout: 5000ms

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  type-aliases-package: com.mining.crypto.vo
  configuration:
    map-underscore-to-camel-case: true

knife4j:
  # 开启增强配置 
  enable: true
  # 生产环境下设为true，屏蔽接口文档
  production: false
  # 开启Swagger的Basic认证功能，默认是false
  basic:
      enable: true
      # Basic认证用户名
      username: test
      # Basic认证密码
      password: 123

jwt:
  secret: testjwt