spring:
  datasource:
    url: jdbc:mysql://103.133.177.231:3306/crypto_mining?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver